replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/gcp-gitops-microservices/capstone-docker-repo/python-api
  tag: 61a70b6
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000