apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-python-api
  labels:
    app: python-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
      - name: python-api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ .Values.env.otelEndpoint }}
        - name: OTEL_SERVICE_NAME
          value: {{ .Values.env.otelServiceName }}
        - name: OTEL_PYTHON_EXCLUDED_URLS
          value: {{ .Values.env.OTEL_PYTHON_EXCLUDED_URLS }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 10