{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-api-ingress
  annotations:
    # Tells GKE to provision an External HTTP(S) Load Balancer
    kubernetes.io/ingress.class: "gce"
    # Bind the Load Balancer to the static IP provisioned in Terraform
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.staticIpName }}
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: python-api-python-api-service
                port:
                  number: {{ .Values.service.port }}
{{- end }}