name: Build and Push Python API

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - '.github/workflows/ci.yaml'

env:
  IMAGE_NAME: python-api

jobs:
  build-scan-and-push:
    runs-on: ubuntu-latest

    environment: dev
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Image Tag
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker Image Locally
        run: |
          # Build it locally first so Trivy can scan it before it touches the cloud
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ./app

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
          format: 'table'
          exit-code: '1' # Fails the pipeline if vulnerabilities are found
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH' # Only fail the build on high or critical CVEs to prevent alert fatigue

      - name: Authenticate to Google Cloud
        # Only authenticate if the Trivy scan passed
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker Auth & Push to Artifact Registry
        run: |
          GAR_HOSTNAME=$(echo "${{ secrets.AR_REPO }}" | cut -d'/' -f1)
          gcloud auth configure-docker $GAR_HOSTNAME --quiet
          
          FULL_IMAGE_PATH="${{ secrets.AR_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          
          # Tag the locally scanned image with the full GAR URL
          docker tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} $FULL_IMAGE_PATH
          
          echo "Pushing verified image: $FULL_IMAGE_PATH"
          docker push $FULL_IMAGE_PATH